name: GitHub Actions Demo
run-name: ${{ github.actor }} is catenating .md files with GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
      - name: Concat document files
        uses: bayssmekanique/action-md-concat@v1
        with:
          srcDir: ./keywords
          destFile: ./glossary.md

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "gabriel@vigliensoni.com"
          git config --local user.name "Gabriel Vigliensoni"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Run: Concatenate .md files."
          git push
